name: Docker Publish

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            arch: arm64
            platform: linux/arm64

    runs-on: ${{ matrix.os }}

    steps:

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short git commit SHA
        id: appvars
        run: |
          calculatedSha=$(git rev-parse --short HEAD)
          branchName=$(git rev-parse --abbrev-ref HEAD)
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
          echo "COMMIT_BRANCH=$branchName" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker - Backend
        id: backend_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner | lower }}/rybbit-backend
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=latest
            type=sha

      - name: Build and push Backend Docker image
        id: backend_build
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          platforms: ${{ matrix.platform }}
          tags: |
            ${{ steps.backend_meta.outputs.tags }}
            ghcr.io/${{ github.repository_owner | lower }}/rybbit-backend:${{ github.ref_name | lower }}-${{ matrix.arch | lower }}
          labels: ${{ steps.backend_meta.outputs.labels }}
          push: true

      - name: Save image digests
        run: |
          mkdir -p ${{ runner.temp }}/digests
          echo "${{ steps.backend_build.outputs.digest }}" > "${{ runner.temp }}/digests/backend-${{ env.PLATFORM_PAIR }}.digest"

      - name: Upload digests
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push Docker manifest
        run: |
          tag=${{ github.ref_name | lower }}
          image=ghcr.io/${{ github.repository_owner }}/rybbit-backend

          docker manifest create $image:$tag \
            $image:${tag}-amd64 \
            $image:${tag}-arm64

          docker manifest push $image:$tag
